Repository boostcampwm-2021/Android09-MountainKing, pull requests merged in 2021-11, with the labels that each got.

#30 [업적] 완료처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/mountainking/MainActivity.kt
  app/src/main/java/com/boostcamp/mountainking/entity/Achievement.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementViewModel.kt
  app/src/main/java/com/boostcamp/mountainking/util/AchievementReceiver.kt
  app/src/main/res/layout/fragment_achievement.xml
Labels: feature, review, review complete

#31 [업적] 카카오톡 공유하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/mountainking/data/Achievements.kt
  app/src/main/java/com/boostcamp/mountainking/entity/Achievement.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementViewModel.kt
  build.gradle
  settings.gradle
Labels: feature, review, review complete

#33 산 기록 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/mountainking/MainActivity.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/LocationService.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/TrackingFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/HistoryFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/HistoryViewModel.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/OnHistoryItemClickListener.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/adapter/HistoryAdapter.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/adapter/HistoryDiffUtilCallback.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/history/adapter/HistoryViewHolder.kt
  app/src/main/res/drawable/ic_baseline_arrow_back_ios_new_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_tracking.xml
  app/src/main/res/layout/item_tracking_history.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: layout, review

#44 Mountain/map
  app/build.gradle
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainFragment.kt
  app/src/main/res/drawable/ic_southkorealow.xml
  app/src/main/res/layout/fragment_mountain.xml
  settings.gradle
Labels: layout

#48 [산 정보] 지역 별 산 리스트 작성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/mountainking/data/City.kt
  app/src/main/java/com/boostcamp/mountainking/data/MountainDao.kt
  app/src/main/java/com/boostcamp/mountainking/data/Repository.kt
  app/src/main/java/com/boostcamp/mountainking/data/RepositoryInterface.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainListFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainListViewModel.kt
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainViewModel.kt
  app/src/main/res/drawable/ic_southkorealow.xml
  app/src/main/res/layout/fragment_mountain_list.xml
  app/src/main/res/navigation/mobile_navigation.xml
  build.gradle
Labels: feature, review

#63 [업적] 버그수정 및 통계와 연결
  app/src/main/java/com/boostcamp/mountainking/data/Achievements.kt
  app/src/main/java/com/boostcamp/mountainking/data/MountainDao.kt
  app/src/main/java/com/boostcamp/mountainking/data/Repository.kt
  app/src/main/java/com/boostcamp/mountainking/data/RepositoryInterface.kt
  app/src/main/java/com/boostcamp/mountainking/data/Statistics.kt
  app/src/main/java/com/boostcamp/mountainking/data/StatisticsDao.kt
  app/src/main/java/com/boostcamp/mountainking/entity/Achievement.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/achievement/AchievementViewModel.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/TrackingFragment.kt
  app/src/main/java/com/boostcamp/mountainking/ui/tracking/TrackingViewModel.kt
  app/src/main/java/com/boostcamp/mountainking/util/Converters.kt
  app/src/main/res/layout/fragment_achievement.xml
  app/src/main/res/layout/fragment_tracking.xml
  app/src/main/res/layout/item_achievement.xml
Labels: feature, fix

#96 feat(mountain): Richpath 버전 이슈 수정
  app/build.gradle
  app/src/main/java/com/boostcamp/mountainking/ui/mountain/MountainFragment.kt
  app/src/main/java/com/richpath/RichPath.kt
  app/src/main/java/com/richpath/RichPathDrawable.kt
  app/src/main/java/com/richpath/RichPathView.kt
  app/src/main/java/com/richpath/listener/OnRichPathUpdatedListener.kt
  app/src/main/java/com/richpath/model/Group.kt
  app/src/main/java/com/richpath/model/Vector.kt
  app/src/main/java/com/richpath/pathparser/PathDataNode.kt
  app/src/main/java/com/richpath/pathparser/PathParser.kt
  app/src/main/java/com/richpath/pathparser/PathParserCompat.kt
  app/src/main/java/com/richpath/pathparser/PathParserCompatApi21.kt
  app/src/main/java/com/richpath/util/PathUtils.kt
  app/src/main/java/com/richpath/util/Utils.kt
  app/src/main/java/com/richpath/util/XmlParser.kt
  app/src/main/res/values/styles.xml
Labels: review
